### ISSUE TITLE
Modificar el valor de retención

### ISSUE THREAD

**Issue by rcarmonad** [muZk/liquido#2]
Según el SII, para el 2021, el valor de retención sube a un 11.5%.
El aumento es gradual según esta tabla: https://www.sii.cl/destacados/boletas_honorarios/aumento_gradual.html

Puede ser que, así como en bolettta, cada uno elija cual es el monto de retención para el calculo o solo dejarlo como fixed de acuerdo con el año en curso.

En fin. Excelente herramienta!

**Comment by muZk** [comment]
Está fixed de acuerdo con el año de la operación renta actual 😮 Como la operación renta actual es 2021, se calcula con la retención del año 2020.

Con respecto a "sueldo líquido" en realidad no importa mucho el porcentaje de boleta, porque independiente de cuanto te retengan, el cálculo final va a ser parecido. La diferencia es que mientras más te retengan = mayor tu saldo a favor = el SII te cobra menos en la próxima declaración.

Ahora bien, esto me lo han comentado harto así que creo que lo más claro es dejarlo con `11.5` 😂

**Comment by muZk** [comment]
Listo. Ahora muestra el líquido considerando la retención de 11.5% y el nuevo tope imponible.
