### ISSUE TITLE
Llamada a API de dólar en pending

### ISSUE THREAD

**Issue by sjamr10** [muZk/liquido#9]
Hola, me ha pasado varias veces que la llamada a la API del dólar se queda en pending por lo q me muestra el sueldo en base a $700 que es bien lejano al precio real actual. Habrá una API del dólar más robusta o será mi Internet?
En cualquier caso creo sería útil mostrar en base a qué precio de dólar se está haciendo el calculo junto al sueldo para saber si es el dólar actual o los $700 sin tener q estar bajando al fondo de la página.
Saludos y gracias!

**Comment by muZk** [comment]
Hola @sjamr10 , acabo de ver tu mensaje.

Muy buena idea, ambas cosas que sugieres son muy buenas alternativas.

Creo que para resolverlo podemos:

- Subir el valor por defecto de 700 a 860 (más cercano al promedio del año)
- Buscar otra API más robusta. Aquí quizás podemos usar las 2 (una nueva y la actual), y que una quede como backup.

@EliAndrea go for it 😄

**Comment by muZk** [comment]
Fixed in #13
